CREATE USER 'i3u'@'localhost' IDENTIFIED BY 'i3u';
GRANT ALL PRIVILEGES ON * . * TO 'i3u'@'localhost' IDENTIFIED BY 'i3u' WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
GRANT ALL PRIVILEGES ON `i3u\_%` . * TO 'i3u'@'localhost';
